import React from 'react';
import {
  Shirt,
  Smartphone,
  UtensilsCrossed,
  Sparkles,
  Activity,
  Car,
  Armchair,
  Home,
  Hammer,
  Wheat,
  GraduationCap,
  Briefcase,
  Truck,
  PartyPopper,
  Zap,
  Wrench,
  ShoppingBag,
  Hotel,
  Church,
  Building2,
  HelpCircle,
  LucideProps,
} from 'lucide-react';

export const CATEGORY_ICON_MAP: Record<string, React.FC<LucideProps>> = {
  Shirt,
  Smartphone,
  UtensilsCrossed,
  Sparkles,
  Activity,
  Car,
  Armchair,
  Home,
  Hammer,
  Wheat,
  GraduationCap,
  Briefcase,
  Truck,
  PartyPopper,
  Zap,
  Wrench,
  ShoppingBag,
  Hotel,
  Church,
  Building2,
  'religious-organizations': Church,
  'cat-religious': Church,
  'accommodation': Hotel,
  'cat-accommodation': Hotel,
  'fashion-apparel': Shirt,
  'cat-fashion': Shirt,
  'electronics-mobile': Smartphone,
  'cat-electronics': Smartphone,
  'food-confectionery': UtensilsCrossed,
  'cat-food': UtensilsCrossed,
  'beauty-personal-care': Sparkles,
  'cat-beauty': Sparkles,
  'health-pharmacy': Activity,
  'cat-health': Activity,
  'automotive-mechanics': Car,
  'cat-auto': Car,
  'home-furniture': Armchair,
  'cat-home': Armchair,
  'real-estate-rentals': Home,
  'cat-real-estate': Home,
  'building-materials-construction': Hammer,
  'cat-building': Hammer,
  'agriculture-produce': Wheat,
  'cat-agric': Wheat,
  'education-training': GraduationCap,
  'cat-education': GraduationCap,
  'professional-services': Briefcase,
  'cat-services': Briefcase,
  'logistics-transport': Truck,
  'cat-logistics': Truck,
  'events-party-rentals': PartyPopper,
  'cat-events': PartyPopper,
  'solar-energy-electricals': Zap,
  'cat-solar': Zap,
  'artisans-skilled-trades': Wrench,
  'cat-artisans': Wrench,
  'supermarkets-groceries': ShoppingBag,
  'cat-supermarkets': ShoppingBag,
};

export function getCategoryIcon(iconName: string, className?: string) {
  const IconComponent = CATEGORY_ICON_MAP[iconName] || Building2;
  return <IconComponent className={className || 'w-5 h-5'} />;
}
